### ISSUE TITLE
Improve JS before moving on to the next version

### ISSUE THREAD

**Issue by vlad-ignatov** [atorov/todoapp#2]
A few things can be changed in the JS to improve it even more:

1. When generating html (and xml) via jQuery, one can treat it as XML, i.e. every tag can be self-closing it empty. For example `$("<button></button>")` can also be `$("<button/>")` which is shorter and easier to read.
2. I would recommend using `jQuery(function($) {...` instead of `$(document).ready(function() {...` because it is shorter and does not assume that the global `$` points to jQuery (jQuery is not the only library using "$").
3. In object literals (unlike in JSON) the labels don't need to be strings unless they are not valid variable names. For example `{ "name" : "whatever" }` is the same as `{ name: "whatever }`. That is not important but can save a few bytes.
4. Most of our code uses 4 spaces for indentation. If possible convert this to 4 spaces so that multiple people can work on it without having to reconfigure their editors.

**Comment by atorov** [comment]
About (.1) -- Use self-closing tags. Done in version 0.2.060210.2.

**Comment by atorov** [comment]
(.2): Use jQuery(function($) {... instead of @(document).ready(function() {... 
Done in version 0.2.060210.3. 

(.3): Object label names. 
Done in version 0.2.060210.3. 

(.4): Support 4 indentation spaces. 
Done in version 0.2.060210.3.

**Comment by atorov** [comment]
I think all is done and this issue should be closed.

**Comment by vlad-ignatov** [comment]
Looks good. Just one hint here:
When you commit, you can include the related issue number in the comment like so `git commit -m "Did something about #2" .`. Multiple tags can be listed too - `git commit -m "Did something #2, #33" .` This way, the commit message will be listed as an entry in the issue comments and there will be a link to the committed changes.

It can even be used to automatically close an issue with something like `fixes #6` or `close #6` or `closes #6` but that is not always the desired effect.
