### ISSUE TITLE
Start using Backbone

### ISSUE THREAD

**Issue by vlad-ignatov** [atorov/todoapp#5]
This is the beginning of the next big step. For now, lets start small and only use Backbone's models and collections. Here is a hint:

1. You will need to have jQuery, Underscore and Backbone included in the page.
2. Then create two classes - one for the todo models and one for the collection that holds those models.
It should be something like this:
```js
var TodoModel = Backbone.Model.extend({ ... });
var TodoCollection = Backbone.collection.extend({
    model: TodoModel,
    // ...
});

var taskList = new TodoCollection(); // Instead of simple array

// Then add new TodoModels to the collection instead of pushing objects
```

P.S. The advantages of this will come later when you can observe the collection and it's models for changes and make your UI dynamic based on that. You can comment here for any related questions.

**Comment by atorov** [comment]
I've created a new branch in this project, called v04. I use Underscore.js and Backbone.js in it. In general, the application keep its functionality - adding tasks, editing and deleting.

Each task is described by the model Task. For the list of tasks is used collection List. I've used two Views. The first one is TaskView -- for individual elements, the second one ListView -- for the entire list. There are not addition/deletion of HTML elements outside of these two Views. The Views manage dynamically content into the list field on the web page. The other three fields - header, input field and footer - are static.

One deficiency of my code: I don't use Namespaces and some variables and functions remain global and accessible from other scripts in the project.

@vlad-ignatov 
When you can, please review my work. Thanks in advance!
